### ISSUE TITLE
Multiple Resource View

### ISSUE THREAD

**Issue by kpilard** [ClickerMonkey/dayspan-vuetify#70] opened 2018-08-29 13:17 UTC
Hey,

A calendar with multiple Resources would be nice.

Something like this
https://dhtmlx.com/docs/products/dhtmlxScheduler/sample_units.shtml

**Comment by ClickerMonkey** [comment] 2018-08-30 02:29
Duplicate of #28

Thanks for the nice visual example! I'll add it to the parent task and close this one.

**Closed by ClickerMonkey** 2018-08-30 02:29 UTC
